### ISSUE TITLE
Why so many different png box art sizes?

### ISSUE THREAD

**Issue by HarryTheTurtle** [libretro-thumbnails/Nintendo_-_Nintendo_64#18]
I was curious to why there are so many varying sizes of thumbnails. As I download the box art and scroll through my collection of N64 games I see the thumbnails jump from size to size with no consistency. Can we come up with a standard size for images other then the less then cap for visual consistency?

I made an entire (USA) collection of high quality N64 box art for my own collection I could share. All images are 360x270 and the file size is 52.4 MB. They are a little larger then the thumbnail display ratio so it scales down rather then scaling up. There is no reason to have images bigger then this it seems because it always scales down. Having images 512x374 seems to just take up disk space. I could be wrong and could use some clarification on this.

**Comment by RobLoach** [comment]
We target 512 pixel width, when available. Feel free to submit a PR if you find any missing.

**Comment by alfrix** [comment]
> There is no reason to have images bigger then this it seems because it always scales down.

High resolution displays (4k is becoming the new standard)

**Comment by HarryTheTurtle** [comment]
When I get some time Ill work on the N64 box arts at 512x374 and make a pull request to update the (USA) releases. Ill work on SNES (USA) releases also. Seems like the naming scheme changed there and they are all different sizes too so Ill try and update those when I get a chance.

**Comment by MarcoEstevez** [comment]
I’m also on it, any help it’s more than welcome 😁

**Comment by HarryTheTurtle** [comment]
May I get clarification on why there are two repositories for Nintendo 64 thumbnails?
This repository does not reflect the changes made recently.
![screenshot 25](https://user-images.githubusercontent.com/47069190/52652225-5618cb80-2eb3-11e9-997f-64549d6944a0.png)
This one does reflect recent changes but can not be downloaded using the online updater.
![screenshot 26](https://user-images.githubusercontent.com/47069190/52652230-5a44e900-2eb3-11e9-9400-21e203ce1e20.png)

Is it that we are updating this separate branch to be merged all at once into the tree for downloading?

**Comment by RobLoach** [comment]
There's just one Nintendo 64 repo:
https://github.com/libretro-thumbnails/Nintendo_-_Nintendo_64

Your first screenshot is an older commit. Likely got to it through the submodule. There's docs on how to bring the changes in from all submodules over at:
https://github.com/libretro-thumbnails/libretro-thumbnails#update

**Comment by HarryTheTurtle** [comment]
I have completed the (USA) update to 512x374 project and it is ready to be merged.
